// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvd-Tna9fQ4mO56-u4hRSuDH2cxB-sOzw',
    appId: '1:292970421105:web:4155c1469ca1fef42434d0',
    messagingSenderId: '292970421105',
    projectId: 'mezan-30b85',
    authDomain: 'mezan-30b85.firebaseapp.com',
    storageBucket: 'mezan-30b85.firebasestorage.app',
    measurementId: 'G-5KWH1PMDB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDKCSqdCqX93BMu6NlzpbK-D77FmQ05Rk',
    appId: '1:292970421105:android:e3d58804fa45f9042434d0',
    messagingSenderId: '292970421105',
    projectId: 'mezan-30b85',
    storageBucket: 'mezan-30b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZKn9rEpTsVixaQuZCX1lV_cVAj6ox90Y',
    appId: '1:292970421105:ios:70d698977db7b3f12434d0',
    messagingSenderId: '292970421105',
    projectId: 'mezan-30b85',
    storageBucket: 'mezan-30b85.firebasestorage.app',
    iosBundleId: 'com.example.faith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZKn9rEpTsVixaQuZCX1lV_cVAj6ox90Y',
    appId: '1:292970421105:ios:70d698977db7b3f12434d0',
    messagingSenderId: '292970421105',
    projectId: 'mezan-30b85',
    storageBucket: 'mezan-30b85.firebasestorage.app',
    iosBundleId: 'com.example.faith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvd-Tna9fQ4mO56-u4hRSuDH2cxB-sOzw',
    appId: '1:292970421105:web:f614ea0a650127752434d0',
    messagingSenderId: '292970421105',
    projectId: 'mezan-30b85',
    authDomain: 'mezan-30b85.firebaseapp.com',
    storageBucket: 'mezan-30b85.firebasestorage.app',
    measurementId: 'G-7FLRF1Z24Q',
  );
}
